### ISSUE TITLE
Issue about code

### ISSUE THREAD

**Issue by LinjieFu-U** [DLR-MI/atme#1]
It's great that you can share this work. I have a question about it. Do you think your ideas are applicable to unsupervised tasks such as CycleGAN? How should I apply it to unsupervised learning image-to-image tasks?

**Comment by sola-ed** [comment]
Hey @flj19951219, thanks for your interest. There are several ways to achieve this, some of which we will be exploring. So stay tuned for updates! Meanwhile, I'll close this, since it is not really an issue.
