### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by joinusers** [DLR-MI/atme#3]
Thanks for your sharing! I am a green hand and keep learing. Having read the paper, I still cannot understand what this model can do. GAN focuses on the generated template, does this model generate a better template? I saw it could make the traditional GAN get a better convergence. In addition, I don't quite understand the meaning of the image given in the paper, does its output mean a transfer of image styles?  Hope to get your answer, thank you very much

**Comment by sola-ed** [comment]
Hello @joinusers, sorry for the late reply. ATME is a model for supervised (a.k.a paired) image-to-image translation. It is a GAN which uses a denoising diffusion process across the epochs, not along an independent time-axis per epoch. This helps to improve the quality of image translation. I invite you to read the references in the paper or other sources to for an overview of the topic. I hope that is clear enough.
